import java.io.File
import java.util.Properties
import java.util.UUID

import org.gradle.api.DefaultTask
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Internal
import org.gradle.api.tasks.TaskAction

plugins {
  alias(libs.plugins.android.application)
  alias(libs.plugins.kotlin.compose)
}

// ---------------------------------------------------------------------------
// Debug keystore: generated automatically at build time with keytool.
// No binary keystore files are stored in the repository; the generation
// command and alias live as plain text inside this file, while the random
// UUID passwords are persisted (gitignored) in debug.keystore.properties so
// subsequent builds can still open the same keystore.
// ---------------------------------------------------------------------------
val debugKeyAlias = "EgyptologyDebugKey"

val debugKeystoreFile = rootProject.file("debug.keystore")
val debugKeystoreProps = rootProject.file("debug.keystore.properties")

// Reuse the stored secret when a keystore was generated by a previous build.
private fun loadStoredSecret(): String? {
  if (!debugKeystoreFile.exists() || !debugKeystoreProps.exists()) return null
  return runCatching {
    Properties().apply { debugKeystoreProps.inputStream().use { load(it) } }
      .getProperty("storePassword")
      ?.takeIf { it.isNotBlank() }
  }.getOrNull()
}

// PKCS12 keystores (the JDK default) require the key password to match the
// store password, so one random UUID secures both.
val debugStorePassword = loadStoredSecret() ?: UUID.randomUUID().toString()
val debugKeyPassword = debugStorePassword

// Generates the keystore on first build only. A dedicated task class with
// injected properties keeps it compatible with the configuration cache.
abstract class GenerateDebugKeystoreTask : DefaultTask() {
  @get:Internal abstract val keystoreFile: RegularFileProperty
  @get:Internal abstract val propsFile: RegularFileProperty
  @get:Internal abstract val keyAlias: Property<String>
  @get:Internal abstract val storePassword: Property<String>
  @get:Internal abstract val keyPassword: Property<String>

  @TaskAction
  fun generate() {
    propsFile.get().asFile.writeText(
      """
      |# Auto-generated by app/build.gradle.kts - do not commit.
      |storePassword=${storePassword.get()}
      |keyPassword=${keyPassword.get()}
      |alias=${keyAlias.get()}
      """.trimMargin()
    )
    val keytool = File(System.getProperty("java.home"), "bin/keytool").absolutePath
    val process = ProcessBuilder(
      keytool, "-genkeypair",
      "-keystore", keystoreFile.get().asFile.absolutePath,
      "-storepass", storePassword.get(),
      "-keypass", keyPassword.get(),
      "-alias", keyAlias.get(),
      "-keyalg", "RSA",
      "-keysize", "2048",
      "-validity", "10000",
      "-dname", "CN=Android Debug,O=Android,C=US"
    ).redirectErrorStream(true).start()
    val output = process.inputStream.bufferedReader().readText()
    if (process.waitFor() == 0) {
      println("Generated debug.keystore.")
    } else {
      throw GradleException("Failed to generate debug.keystore: $output")
    }
  }
}

val generateDebugKeystore = tasks.register<GenerateDebugKeystoreTask>("generateDebugKeystore") {
  group = "build"
  description = "Generates debug.keystore with keytool if it does not exist."
  keystoreFile.set(debugKeystoreFile)
  propsFile.set(debugKeystoreProps)
  keyAlias.set(debugKeyAlias)
  storePassword.set(debugStorePassword)
  keyPassword.set(debugKeyPassword)
  onlyIf {
    !keystoreFile.get().asFile.exists() || !propsFile.get().asFile.exists()
  }
}

// Signing happens in packaging/validation tasks - make sure they run after generation.
tasks.matching {
  it.name.startsWith("package") || it.name.startsWith("validateSigning")
}.configureEach {
  dependsOn(generateDebugKeystore)
}

android {
  namespace = "com.negm.egyptology"
  compileSdk { version = release(36) { minorApiLevel = 1 } }

  defaultConfig {
    applicationId = "com.negm.egyptology"
    minSdk = 24
    targetSdk = 36
    versionCode = 1
    versionName = "1.0"
  }

  signingConfigs {
    create("debugConfig") {
      storeFile = debugKeystoreFile
      storePassword = debugStorePassword
      keyAlias = debugKeyAlias
      keyPassword = debugKeyPassword
    }
    create("release") {
      val envKeystore = System.getenv("KEYSTORE_PATH")
      val keyFile = when {
        !envKeystore.isNullOrBlank() && file(envKeystore).exists() -> file(envKeystore)
        file("${rootDir}/my-upload-key.jks").exists() -> file("${rootDir}/my-upload-key.jks")
        else -> null
      }
      if (keyFile != null) {
        storeFile = keyFile
        storePassword = System.getenv("STORE_PASSWORD") ?: debugStorePassword
        keyAlias = System.getenv("KEY_ALIAS") ?: debugKeyAlias
        keyPassword = System.getenv("KEY_PASSWORD") ?: debugKeyPassword
      } else {
        // Fall back to the auto-generated debug.keystore so CI builds always sign.
        storeFile = debugKeystoreFile
        storePassword = debugStorePassword
        keyAlias = debugKeyAlias
        keyPassword = debugKeyPassword
      }
    }
  }

  buildTypes {
    release {
      isCrunchPngs = false
      isMinifyEnabled = false
      isShrinkResources = false
      proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
      signingConfig = signingConfigs.getByName("release")
    }
    debug {
      signingConfig = signingConfigs.getByName("debugConfig")
    }
  }

  packaging {
    resources {
      excludes += setOf(
        "META-INF/DEPENDENCIES",
        "META-INF/LICENSE",
        "META-INF/LICENSE.txt",
        "META-INF/license.txt",
        "META-INF/NOTICE",
        "META-INF/NOTICE.txt",
        "META-INF/notice.txt",
        "META-INF/*.kotlin_module",
        "META-INF/AL2.0",
        "META-INF/LGPL2.1"
      )
    }
  }
  compileOptions {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
  }
  buildFeatures {
    compose = true
    buildConfig = true
  }
  dependenciesInfo {
    includeInApk = false
    includeInBundle = true
  }
}

dependencies {
  implementation(platform(libs.androidx.compose.bom))
  implementation(libs.androidx.activity.compose)
  implementation(libs.androidx.compose.material.icons.core)
  implementation(libs.androidx.compose.material.icons.extended)
  implementation(libs.androidx.compose.material3)
  implementation(libs.androidx.compose.ui)
  implementation(libs.androidx.compose.ui.graphics)
  implementation(libs.androidx.compose.ui.tooling.preview)
  implementation(libs.androidx.core.ktx)
  implementation(libs.androidx.lifecycle.runtime.compose)
  implementation(libs.androidx.lifecycle.runtime.ktx)
  implementation(libs.androidx.lifecycle.viewmodel.compose)
  implementation(libs.androidx.navigation.compose)
  implementation(libs.kotlinx.coroutines.android)
  implementation(libs.kotlinx.coroutines.core)
  debugImplementation(libs.androidx.compose.ui.tooling)
}
